# From Statistical Physics to Data-Driven Modelling with Applications to Quantitative Biology
Tutorial 8 : Hidden Markov Models for CG content variations in viral genomes.

This tutorial is based on the Chapter 3 of the book:
     R. Durbin, S. Eddy, A. Krogh, G. Mitchison, Biological sequence analysis, Cambridge University Press 2007. 

Starting Notebook SC RM FZ.

In [1]:
#Information, Inference Networks: Tutorial 6.  S.C., R.M., F.Z.
#Hidden Markov Model
import numpy as np
import math
import matplotlib.pyplot as plt
from scipy.sparse import coo_matrix
import numpy.matlib
%matplotlib inline
#plt.rcParams["font.family"] = "serif"
#plt.rcParams["mathtext.fontset"] = "dejavuserif"
#plt.rcParams["figure.figsize"] = (10, 8)
#plt.rcParams["font.size"] = 26

import numpy.linalg as LA
from numpy.linalg import inv

In [2]:
#Function to convert the basis letters into integer numbers from 1 to 4 
def letter2number(a): 
    
    switcher = {
        'a': 1,
        'c': 2,
        'g': 3,
        't': 4,
    }
    return switcher.get(a,0)

Read Lambda phage genome.

In [5]:
# Read a Sequence data and return a sequence of  numbers
# Open the file and write a list containing all lines. Join them.
data=open('./Data/lambdaphage.txt', 'r')
phageread1 = data.readlines()
phageread2 = ''.join(phageread1)
data.close()
# Convert the letters into numbers from 0 to 3
seq = []
for i in range(len(phageread2)):
    y = letter2number(phageread2[i])
    if (y!=0):
        seq.append(y-1)
L=len(seq)
print(L)

48502


Define emission probabilities for AT and GC rich regions.

In [10]:
E=np.zeros((2,4))
E[0,:]=np.array([0.2700,0.2084,0.1981,0.3235])   #type 0 is AT-rich
E[1,:]=np.array([0.2462,0.2476,0.2985,0.2077])   #type 1 is CG-rich


[[0.27   0.2084 0.1981 0.3235]
 [0.2462 0.2476 0.2985 0.2077]] 
 [-0.09227775  0.17235523  0.40999798 -0.44310438]


Question 2: Decide the type (AT or GC rich) of a sequence by using Bayesian inference, guess the type for the the first and second halves of the genome.

Question 3: Compute the average CG content of a sequence.

Question 5: Implement the Viterbi algorithm,

Questions 4 and 5: Plot the decision and the average CG content on a width k.